spotify_client_id: "" # Google how to get this value
spotify_client_secret: ""
spotify_redirect_uri: "http://localhost:8888/callback" # leave as is

dj_library_directory: "E:\\" # Director of your usb and program output
tracks_folder: "Pysync_d DJ Tracks" # Folder name for location of saved audio files
serato_subcrate_dir: "_Serato_\\Subcrates" # Location of your serato subcrates
rekordbox_playlist_folder: "Rekordbox Playlist Import Files" # Folder name for location of saved rekordbox m3u files

download_liked_songs: true # Should download users liked songs? (true/false)
liked_songs_track_limit: 50  # How many of your liked songs to download (integer)
liked_songs_date_limit: null # Date to download back to (DD-MM-YYYY)

playlists_to_download:
  PLaylist1: "2rBDG7m5QcjM3OjHyorkMZ" # Can use either just playlist id
  Playlist2: "https://open.spotify.com/playlist/2rBDG7m5QcjM3OjHyorkMZ" # or full url