name: Compile Program Ready For Download
on:
  push:
    branches:
      - 'main'
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Install Requirements.txt
        run: 'pip install nicegui pywebview'
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'PySyncDj.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'PySync DJ Windows'

  pyinstaller-build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install gettext dependency
        run: |
          brew install gettext
          brew link --force gettext

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'PySyncDj.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'PySync DJ Mac'