name: Compile Program for Mac
on:
  push:
    branches:
      - 'main'
jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Install Requirements.txt
        run: 'pip install nicegui pywebview'
      - name: Create Mac Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'PySyncDj.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'PySync DJ'